# Generated by Django 4.2.6 on 2023-10-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=100)),
                ("book_category", models.CharField(max_length=50)),
                ("book_description", models.TextField(max_length=10000)),
                ("book_rating", models.FloatField()),
                ("book_image", models.CharField(max_length=100)),
            ],
        ),
    ]
